language: python
python: "3.7"
env:
  - TOX_ENV=py37
  - TOX_ENV=black
  - TOX_ENV=flake8
  - TOX_ENV=pylint
  - TOX_ENV=bandit
  - TOX_ENV=mypy
  - TOX_ENV=docs
matrix:
  include:
    - python: "3.6"
      env: TOX_ENV=py36
install:
  - pip install tox pip-tools
script:
  - pip-sync requirements-dev.txt
  - tox -e $TOX_ENV
